### ISSUE TITLE
Hand-crafted?

### ISSUE THREAD

**Issue by TomSwift** [richardwilkes/cskia#4]
@richardwilkes are the definitions in `sk_capi` hand-crafted or do you have a tool to generate them somehow?   I'm adding a handful that I need by hand and it got me wondering.

**Comment by richardwilkes** [comment]
I’m afraid they are hand-crafted. I did have some code that tried to auto-gen stuff at one point, but kept running into issues — C++ just has too many special cases when parsing and I eventually just decided to do things by hand.
